
export interface NewsItem {
  id: string;
  title: string;
  excerpt: string;
  date: string;
  category: string;
  entity: string;
  image: string;
  content: {
    introduction: string;
    sections: {
      heading: string;
      content: string;
    }[];
    conclusion: string;
  };
}

export const newsData: NewsItem[] = [
  {
    id: "akoula-ai-platform-2025",
    title: "AKOULA Launches Revolutionary AI-Powered Agro-Industrial Platform Suite",
    excerpt: "AKOULA unveils comprehensive AI solutions including Quote Builder, equipment marketplace, and training platform targeting West and Central Africa's agro-industrial sector.",
    date: "April 1, 2025",
    category: "AI Innovation",
    entity: "AKOULA",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    content: {
      introduction: "AKOULA's groundbreaking AI-powered platform suite represents a paradigm shift in West and Central Africa's agro-industrial landscape, addressing critical gaps in smart industrial intelligence.",
      sections: [
        {
          heading: "Revolutionary Platform Components",
          content: "The integrated suite features three core components: an intelligent Quote Builder that streamlines procurement processes, a comprehensive Africa-ready industrial equipment marketplace connecting suppliers with buyers, and an innovative online training platform designed specifically for industry operators across the region."
        },
        {
          heading: "Addressing Local Challenges",
          content: "These platforms tackle pressing regional challenges including limited access to industrial equipment, lack of standardized pricing mechanisms, and insufficient technical training opportunities. The AI-powered solutions provide localized intelligence adapted to African markets and operational conditions."
        },
        {
          heading: "OWL International Synergies",
          content: "This launch creates powerful synergies across OWL's portfolio, with CAOAGRO.COM leveraging the equipment marketplace for project implementations and OWLOMA benefiting from industrial real estate insights generated by platform data."
        }
      ],
      conclusion: "AKOULA's platform suite positions OWL International at the forefront of Africa's digital industrial transformation, creating sustainable value chains and fostering regional economic development."
    }
  },
  {
    id: "caoagro-shea-butter-contract-2025",
    title: "CAOAGRO.COM Secures Major Contract for Côte d'Ivoire's First Industrial Shea Butter Plant",
    excerpt: "CAOAGRO.COM wins double contract to build and install 6T/h biomass boiler and main processing equipment for Côte d'Ivoire's pioneering industrial shea butter production facility.",
    date: "June 17, 2025",
    category: "Industrial Development",
    entity: "CAOAGRO.COM",
    image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    content: {
      introduction: "CAOAGRO.COM's landmark contract marks a historic milestone in West Africa's industrial development, establishing Côte d'Ivoire's first large-scale shea butter production facility.",
      sections: [
        {
          heading: "Project Specifications",
          content: "The comprehensive project includes the design, construction, and installation of a 6-tonne per hour biomass boiler system and complete main processing equipment area. This state-of-the-art facility will process raw shea nuts into premium shea butter and value-added derivatives for both domestic and international markets."
        },
        {
          heading: "African Shea Industry Impact",
          content: "Africa produces 90% of the world's shea nuts, yet most are exported raw, missing value-addition opportunities. This facility will capture significant value locally, creating jobs, supporting rural communities, and establishing Côte d'Ivoire as a regional processing hub for shea products."
        },
        {
          heading: "Sustainable Technology Integration",
          content: "The biomass boiler utilizes agricultural waste as fuel, creating a circular economy model that reduces environmental impact while providing sustainable energy for production processes. This approach aligns with global sustainability trends and reduces operational costs."
        }
      ],
      conclusion: "This project demonstrates CAOAGRO.COM's capability to deliver complex industrial solutions while contributing to Africa's industrial transformation and sustainable development goals."
    }
  },
  {
    id: "caoagro-truck-dealership-2025",
    title: "CAOAGRO.COM Finalizes Exclusive Discussions for West Africa Truck Dealership Headquarters",
    excerpt: "CAOAGRO.COM approaches final stages of exclusive negotiations to establish a major truck dealership's regional headquarters in Abidjan, featuring 3D renderings for 3.5-hectare development.",
    date: "June 6, 2025",
    category: "Infrastructure Development",
    entity: "CAOAGRO.COM",
    image: "https://images.unsplash.com/photo-1558618666-f4dcd8e1a5c0?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    content: {
      introduction: "CAOAGRO.COM's strategic positioning in Abidjan's automotive sector expansion represents a significant milestone in West Africa's commercial vehicle infrastructure development.",
      sections: [
        {
          heading: "Project Scope and Scale",
          content: "The ambitious development spans 3.5 hectares in Abidjan's new northern industrial area, featuring comprehensive facilities including showrooms, service centers, parts warehouses, and administrative offices. Detailed architectural studies and 3D renderings showcase phased development from intermediate to final implementation stages."
        },
        {
          heading: "Strategic Location Advantages",
          content: "Abidjan's position as West Africa's economic hub, combined with improved infrastructure and port access, makes it the ideal location for regional headquarters. The northern industrial area offers modern utilities, transportation links, and room for future expansion."
        },
        {
          heading: "Regional Market Impact",
          content: "This headquarters will serve as the distribution and service hub for multiple West African markets, creating employment opportunities, enhancing regional logistics capabilities, and supporting the growing demand for commercial vehicles across the region."
        }
      ],
      conclusion: "The successful completion of this project will establish CAOAGRO.COM as a key player in West Africa's automotive infrastructure development while strengthening regional economic integration."
    }
  },
  {
    id: "caoagro-hevea-technology-2025",
    title: "CAOAGRO.COM Pioneers Hevea Tree Seed Processing Technology Development",
    excerpt: "CAOAGRO.COM orders comprehensive business plans for innovative local processing technologies to transform vast quantities of underutilized Hevea tree seeds into valuable industrial products.",
    date: "January 15, 2025",
    category: "Sustainable Technology",
    entity: "CAOAGRO.COM",
    image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    content: {
      introduction: "CAOAGRO.COM's initiative to develop Hevea seed processing technologies addresses a massive waste stream while creating new value chains in rubber-producing regions across Africa.",
      sections: [
        {
          heading: "The Untapped Resource",
          content: "Millions of tons of Hevea tree seeds are discarded annually across Africa's rubber plantations, representing an enormous waste of potential raw materials. These seeds contain valuable oils, proteins, and other compounds suitable for industrial applications, cosmetics, and agricultural uses."
        },
        {
          heading: "Processing Technology and Applications",
          content: "Advanced processing technologies can extract high-quality oils for biodiesel production, protein meal for animal feed, and specialized compounds for cosmetic and pharmaceutical applications. The development focuses on cost-effective, locally-adaptable processing methods suitable for African conditions."
        },
        {
          heading: "Economic and Environmental Impact",
          content: "Transforming waste into valuable products creates new revenue streams for rubber farmers, reduces environmental waste, and establishes sustainable circular economy models. The technology transfer will support local job creation and skill development while contributing to Africa's industrial diversification."
        }
      ],
      conclusion: "This pioneering initiative positions CAOAGRO.COM at the forefront of sustainable industrial innovation, creating value from waste while supporting rural economic development across Africa."
    }
  },
  {
    id: "owloma-launch-announcement-2025",
    title: "OWLOMA: OWL International's New Real Estate Entity Set to Launch S1 2026",
    excerpt: "OWLOMA emerges as OWL International's latest entity, targeting improved real estate markets in West Africa and Western Europe while supporting young businesses with property ownership solutions.",
    date: "April 22, 2025",
    category: "Portfolio Expansion",
    entity: "OWLOMA",
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    content: {
      introduction: "OWLOMA's strategic launch represents OWL International's expansion into real estate, capitalizing on improving market conditions across West Africa and Western Europe while creating synergies with existing portfolio companies.",
      sections: [
        {
          heading: "Market Opportunity Assessment",
          content: "Recent improvements in West African real estate markets, combined with stable conditions in Western Europe, create attractive investment opportunities. OWLOMA will focus on commercial and industrial properties that support business development while generating sustainable returns for OWL International's portfolio."
        },
        {
          heading: "Supporting Young Business Growth",
          content: "OWLOMA's unique value proposition includes helping promising young businesses achieve property ownership, creating a stable foundation for growth and long-term success. This approach builds a backbone for sustainable business development while generating rental income and capital appreciation."
        },
        {
          heading: "Portfolio Integration Strategy",
          content: "OWLOMA will work closely with other OWL entities, potentially providing real estate solutions for CAOAGRO.COM's industrial projects and AKOULA's platform infrastructure requirements. This integration creates cross-portfolio value and operational efficiencies."
        }
      ],
      conclusion: "OWLOMA's launch in S1 2026 will further diversify OWL International's portfolio while creating a supportive ecosystem for business growth across two dynamic continental markets."
    }
  }
];
